// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: images.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearImages = `-- name: ClearImages :exec
DELETE FROM images WHERE project_id = ?
`

func (q *Queries) ClearImages(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, clearImages, projectID)
	return err
}

const getDefaultImage = `-- name: GetDefaultImage :one
SELECT id, path FROM images WHERE project_id = ? AND is_default = 1
`

type GetDefaultImageRow struct {
	ID   string `json:"id"`
	Path string `json:"path"`
}

func (q *Queries) GetDefaultImage(ctx context.Context, projectID string) (GetDefaultImageRow, error) {
	row := q.db.QueryRowContext(ctx, getDefaultImage, projectID)
	var i GetDefaultImageRow
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const getImages = `-- name: GetImages :many
SELECT id, project_id, path, caption, tags, style, notes, is_default 
FROM images WHERE project_id = ?
`

func (q *Queries) GetImages(ctx context.Context, projectID string) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getImages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Path,
			&i.Caption,
			&i.Tags,
			&i.Style,
			&i.Notes,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const imageCatalogExists = `-- name: ImageCatalogExists :one
SELECT EXISTS(SELECT 1 FROM images WHERE project_id = ?)
`

func (q *Queries) ImageCatalogExists(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, imageCatalogExists, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveImage = `-- name: SaveImage :exec
INSERT INTO images (id, project_id, path, caption, tags, style, notes, is_default)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id, project_id) DO UPDATE SET 
    caption = excluded.caption, 
    tags = excluded.tags,
    style = excluded.style,
    notes = excluded.notes,
    is_default = excluded.is_default
`

type SaveImageParams struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"project_id"`
	Path      string         `json:"path"`
	Caption   sql.NullString `json:"caption"`
	Tags      sql.NullString `json:"tags"`
	Style     sql.NullInt64  `json:"style"`
	Notes     sql.NullString `json:"notes"`
	IsDefault sql.NullInt64  `json:"is_default"`
}

func (q *Queries) SaveImage(ctx context.Context, arg SaveImageParams) error {
	_, err := q.db.ExecContext(ctx, saveImage,
		arg.ID,
		arg.ProjectID,
		arg.Path,
		arg.Caption,
		arg.Tags,
		arg.Style,
		arg.Notes,
		arg.IsDefault,
	)
	return err
}
