// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Image struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"project_id"`
	Path      string         `json:"path"`
	Caption   sql.NullString `json:"caption"`
	Tags      sql.NullString `json:"tags"`
	Style     sql.NullInt64  `json:"style"`
	Notes     sql.NullString `json:"notes"`
	IsDefault sql.NullInt64  `json:"is_default"`
}

type Project struct {
	ID         string         `json:"id"`
	AudioPath  string         `json:"audio_path"`
	ImagesDir  string         `json:"images_dir"`
	OutputDir  string         `json:"output_dir"`
	AudioHash  string         `json:"audio_hash"`
	ImagesHash string         `json:"images_hash"`
	Settings   sql.NullString `json:"settings"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type ProjectSetting struct {
	ProjectID          string          `json:"project_id"`
	Shader             sql.NullString  `json:"shader"`
	Fps                sql.NullInt64   `json:"fps"`
	Aspects            sql.NullString  `json:"aspects"`
	FontSize           sql.NullInt64   `json:"font_size"`
	SubtitleMargin     sql.NullInt64   `json:"subtitle_margin"`
	MinShotSec         sql.NullFloat64 `json:"min_shot_sec"`
	MaxWords           sql.NullInt64   `json:"max_words"`
	DefaultImageWeight sql.NullFloat64 `json:"default_image_weight"`
	TitleWeight        sql.NullString  `json:"title_weight"`
	BlurStrength       sql.NullInt64   `json:"blur_strength"`
	WhisperModel       sql.NullString  `json:"whisper_model"`
	VisionModel        sql.NullString  `json:"vision_model"`
	SelectModel        sql.NullString  `json:"select_model"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
}

type Segment struct {
	ID        int64   `json:"id"`
	ProjectID string  `json:"project_id"`
	Start     float64 `json:"start"`
	End       float64 `json:"end"`
	Text      string  `json:"text"`
	Ordinal   int64   `json:"ordinal"`
}

type TextWindow struct {
	ID        int64          `json:"id"`
	ProjectID string         `json:"project_id"`
	Start     float64        `json:"start"`
	End       float64        `json:"end"`
	Text      sql.NullString `json:"text"`
	Ordinal   int64          `json:"ordinal"`
}

type TimelineEntry struct {
	ID         int64           `json:"id"`
	ProjectID  string          `json:"project_id"`
	Start      float64         `json:"start"`
	End        float64         `json:"end"`
	ImageID    string          `json:"image_id"`
	ImagePath  string          `json:"image_path"`
	Confidence sql.NullFloat64 `json:"confidence"`
	Reason     sql.NullString  `json:"reason"`
	Shader     sql.NullString  `json:"shader"`
	Ordinal    int64           `json:"ordinal"`
}

type Transcript struct {
	ProjectID   string          `json:"project_id"`
	Language    sql.NullString  `json:"language"`
	DurationSec sql.NullFloat64 `json:"duration_sec"`
}
