// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :exec
INSERT OR IGNORE INTO projects (id, audio_path, images_dir, output_dir, audio_hash, images_hash, settings)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID         string         `json:"id"`
	AudioPath  string         `json:"audio_path"`
	ImagesDir  string         `json:"images_dir"`
	OutputDir  string         `json:"output_dir"`
	AudioHash  string         `json:"audio_hash"`
	ImagesHash string         `json:"images_hash"`
	Settings   sql.NullString `json:"settings"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.AudioPath,
		arg.ImagesDir,
		arg.OutputDir,
		arg.AudioHash,
		arg.ImagesHash,
		arg.Settings,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, audio_path, images_dir, output_dir, audio_hash, images_hash, settings, created_at FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.AudioPath,
		&i.ImagesDir,
		&i.OutputDir,
		&i.AudioHash,
		&i.ImagesHash,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(SELECT 1 FROM projects WHERE id = ?)
`

func (q *Queries) ProjectExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
