// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: project_settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProjectSettings = `-- name: CreateProjectSettings :exec
INSERT INTO project_settings (project_id) VALUES (?)
`

func (q *Queries) CreateProjectSettings(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, createProjectSettings, projectID)
	return err
}

const getProjectSettings = `-- name: GetProjectSettings :one
SELECT project_id, shader, fps, aspects, font_size, subtitle_margin, min_shot_sec, max_words, default_image_weight, title_weight, blur_strength, whisper_model, vision_model, select_model, created_at, updated_at FROM project_settings WHERE project_id = ?
`

func (q *Queries) GetProjectSettings(ctx context.Context, projectID string) (ProjectSetting, error) {
	row := q.db.QueryRowContext(ctx, getProjectSettings, projectID)
	var i ProjectSetting
	err := row.Scan(
		&i.ProjectID,
		&i.Shader,
		&i.Fps,
		&i.Aspects,
		&i.FontSize,
		&i.SubtitleMargin,
		&i.MinShotSec,
		&i.MaxWords,
		&i.DefaultImageWeight,
		&i.TitleWeight,
		&i.BlurStrength,
		&i.WhisperModel,
		&i.VisionModel,
		&i.SelectModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectSettings = `-- name: UpdateProjectSettings :exec
UPDATE project_settings SET 
    shader = ?,
    fps = ?,
    aspects = ?,
    font_size = ?,
    subtitle_margin = ?,
    min_shot_sec = ?,
    max_words = ?,
    default_image_weight = ?,
    title_weight = ?,
    blur_strength = ?,
    whisper_model = ?,
    vision_model = ?,
    select_model = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE project_id = ?
`

type UpdateProjectSettingsParams struct {
	Shader             sql.NullString  `json:"shader"`
	Fps                sql.NullInt64   `json:"fps"`
	Aspects            sql.NullString  `json:"aspects"`
	FontSize           sql.NullInt64   `json:"font_size"`
	SubtitleMargin     sql.NullInt64   `json:"subtitle_margin"`
	MinShotSec         sql.NullFloat64 `json:"min_shot_sec"`
	MaxWords           sql.NullInt64   `json:"max_words"`
	DefaultImageWeight sql.NullFloat64 `json:"default_image_weight"`
	TitleWeight        sql.NullString  `json:"title_weight"`
	BlurStrength       sql.NullInt64   `json:"blur_strength"`
	WhisperModel       sql.NullString  `json:"whisper_model"`
	VisionModel        sql.NullString  `json:"vision_model"`
	SelectModel        sql.NullString  `json:"select_model"`
	ProjectID          string          `json:"project_id"`
}

func (q *Queries) UpdateProjectSettings(ctx context.Context, arg UpdateProjectSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectSettings,
		arg.Shader,
		arg.Fps,
		arg.Aspects,
		arg.FontSize,
		arg.SubtitleMargin,
		arg.MinShotSec,
		arg.MaxWords,
		arg.DefaultImageWeight,
		arg.TitleWeight,
		arg.BlurStrength,
		arg.WhisperModel,
		arg.VisionModel,
		arg.SelectModel,
		arg.ProjectID,
	)
	return err
}

const upsertProjectSettings = `-- name: UpsertProjectSettings :exec
INSERT INTO project_settings (
    project_id, shader, fps, aspects, font_size, subtitle_margin,
    min_shot_sec, max_words, default_image_weight, title_weight, blur_strength,
    whisper_model, vision_model, select_model
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id) DO UPDATE SET
    shader = excluded.shader,
    fps = excluded.fps,
    aspects = excluded.aspects,
    font_size = excluded.font_size,
    subtitle_margin = excluded.subtitle_margin,
    min_shot_sec = excluded.min_shot_sec,
    max_words = excluded.max_words,
    default_image_weight = excluded.default_image_weight,
    title_weight = excluded.title_weight,
    blur_strength = excluded.blur_strength,
    whisper_model = excluded.whisper_model,
    vision_model = excluded.vision_model,
    select_model = excluded.select_model,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertProjectSettingsParams struct {
	ProjectID          string          `json:"project_id"`
	Shader             sql.NullString  `json:"shader"`
	Fps                sql.NullInt64   `json:"fps"`
	Aspects            sql.NullString  `json:"aspects"`
	FontSize           sql.NullInt64   `json:"font_size"`
	SubtitleMargin     sql.NullInt64   `json:"subtitle_margin"`
	MinShotSec         sql.NullFloat64 `json:"min_shot_sec"`
	MaxWords           sql.NullInt64   `json:"max_words"`
	DefaultImageWeight sql.NullFloat64 `json:"default_image_weight"`
	TitleWeight        sql.NullString  `json:"title_weight"`
	BlurStrength       sql.NullInt64   `json:"blur_strength"`
	WhisperModel       sql.NullString  `json:"whisper_model"`
	VisionModel        sql.NullString  `json:"vision_model"`
	SelectModel        sql.NullString  `json:"select_model"`
}

func (q *Queries) UpsertProjectSettings(ctx context.Context, arg UpsertProjectSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectSettings,
		arg.ProjectID,
		arg.Shader,
		arg.Fps,
		arg.Aspects,
		arg.FontSize,
		arg.SubtitleMargin,
		arg.MinShotSec,
		arg.MaxWords,
		arg.DefaultImageWeight,
		arg.TitleWeight,
		arg.BlurStrength,
		arg.WhisperModel,
		arg.VisionModel,
		arg.SelectModel,
	)
	return err
}
