// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: timeline.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearTimeline = `-- name: ClearTimeline :exec
DELETE FROM timeline_entries WHERE project_id = ?
`

func (q *Queries) ClearTimeline(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, clearTimeline, projectID)
	return err
}

const getTimeline = `-- name: GetTimeline :many
SELECT id, project_id, start, "end", image_id, image_path, confidence, reason, shader, ordinal 
FROM timeline_entries WHERE project_id = ? ORDER BY ordinal
`

func (q *Queries) GetTimeline(ctx context.Context, projectID string) ([]TimelineEntry, error) {
	rows, err := q.db.QueryContext(ctx, getTimeline, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineEntry{}
	for rows.Next() {
		var i TimelineEntry
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Start,
			&i.End,
			&i.ImageID,
			&i.ImagePath,
			&i.Confidence,
			&i.Reason,
			&i.Shader,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTimelineEntry = `-- name: SaveTimelineEntry :exec
INSERT INTO timeline_entries (project_id, start, "end", image_id, image_path, confidence, reason, shader, ordinal)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type SaveTimelineEntryParams struct {
	ProjectID  string          `json:"project_id"`
	Start      float64         `json:"start"`
	End        float64         `json:"end"`
	ImageID    string          `json:"image_id"`
	ImagePath  string          `json:"image_path"`
	Confidence sql.NullFloat64 `json:"confidence"`
	Reason     sql.NullString  `json:"reason"`
	Shader     sql.NullString  `json:"shader"`
	Ordinal    int64           `json:"ordinal"`
}

func (q *Queries) SaveTimelineEntry(ctx context.Context, arg SaveTimelineEntryParams) error {
	_, err := q.db.ExecContext(ctx, saveTimelineEntry,
		arg.ProjectID,
		arg.Start,
		arg.End,
		arg.ImageID,
		arg.ImagePath,
		arg.Confidence,
		arg.Reason,
		arg.Shader,
		arg.Ordinal,
	)
	return err
}

const timelineExists = `-- name: TimelineExists :one
SELECT EXISTS(SELECT 1 FROM timeline_entries WHERE project_id = ?)
`

func (q *Queries) TimelineExists(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, timelineExists, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSegmentShader = `-- name: UpdateSegmentShader :exec
UPDATE timeline_entries SET shader = ? WHERE id = ? AND project_id = ?
`

type UpdateSegmentShaderParams struct {
	Shader    sql.NullString `json:"shader"`
	ID        int64          `json:"id"`
	ProjectID string         `json:"project_id"`
}

func (q *Queries) UpdateSegmentShader(ctx context.Context, arg UpdateSegmentShaderParams) error {
	_, err := q.db.ExecContext(ctx, updateSegmentShader, arg.Shader, arg.ID, arg.ProjectID)
	return err
}
