// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transcripts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearSegments = `-- name: ClearSegments :exec
DELETE FROM segments WHERE project_id = ?
`

func (q *Queries) ClearSegments(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, clearSegments, projectID)
	return err
}

const getSegments = `-- name: GetSegments :many
SELECT id, project_id, start, "end", text, ordinal FROM segments 
WHERE project_id = ? ORDER BY ordinal
`

func (q *Queries) GetSegments(ctx context.Context, projectID string) ([]Segment, error) {
	rows, err := q.db.QueryContext(ctx, getSegments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Segment{}
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Start,
			&i.End,
			&i.Text,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranscript = `-- name: GetTranscript :one
SELECT project_id, language, duration_sec FROM transcripts WHERE project_id = ?
`

func (q *Queries) GetTranscript(ctx context.Context, projectID string) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, getTranscript, projectID)
	var i Transcript
	err := row.Scan(&i.ProjectID, &i.Language, &i.DurationSec)
	return i, err
}

const saveSegment = `-- name: SaveSegment :exec
INSERT INTO segments (project_id, start, "end", text, ordinal)
VALUES (?, ?, ?, ?, ?)
`

type SaveSegmentParams struct {
	ProjectID string  `json:"project_id"`
	Start     float64 `json:"start"`
	End       float64 `json:"end"`
	Text      string  `json:"text"`
	Ordinal   int64   `json:"ordinal"`
}

func (q *Queries) SaveSegment(ctx context.Context, arg SaveSegmentParams) error {
	_, err := q.db.ExecContext(ctx, saveSegment,
		arg.ProjectID,
		arg.Start,
		arg.End,
		arg.Text,
		arg.Ordinal,
	)
	return err
}

const saveTranscript = `-- name: SaveTranscript :exec
INSERT INTO transcripts (project_id, language, duration_sec)
VALUES (?, ?, ?)
ON CONFLICT(project_id) DO UPDATE SET language = excluded.language, duration_sec = excluded.duration_sec
`

type SaveTranscriptParams struct {
	ProjectID   string          `json:"project_id"`
	Language    sql.NullString  `json:"language"`
	DurationSec sql.NullFloat64 `json:"duration_sec"`
}

func (q *Queries) SaveTranscript(ctx context.Context, arg SaveTranscriptParams) error {
	_, err := q.db.ExecContext(ctx, saveTranscript, arg.ProjectID, arg.Language, arg.DurationSec)
	return err
}

const transcriptExists = `-- name: TranscriptExists :one
SELECT EXISTS(SELECT 1 FROM transcripts WHERE project_id = ?)
`

func (q *Queries) TranscriptExists(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, transcriptExists, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
