// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: windows.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearWindows = `-- name: ClearWindows :exec
DELETE FROM text_windows WHERE project_id = ?
`

func (q *Queries) ClearWindows(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, clearWindows, projectID)
	return err
}

const getWindows = `-- name: GetWindows :many
SELECT id, project_id, start, "end", text, ordinal FROM text_windows 
WHERE project_id = ? ORDER BY ordinal
`

func (q *Queries) GetWindows(ctx context.Context, projectID string) ([]TextWindow, error) {
	rows, err := q.db.QueryContext(ctx, getWindows, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TextWindow{}
	for rows.Next() {
		var i TextWindow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Start,
			&i.End,
			&i.Text,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveWindow = `-- name: SaveWindow :exec
INSERT INTO text_windows (project_id, start, "end", text, ordinal)
VALUES (?, ?, ?, ?, ?)
`

type SaveWindowParams struct {
	ProjectID string         `json:"project_id"`
	Start     float64        `json:"start"`
	End       float64        `json:"end"`
	Text      sql.NullString `json:"text"`
	Ordinal   int64          `json:"ordinal"`
}

func (q *Queries) SaveWindow(ctx context.Context, arg SaveWindowParams) error {
	_, err := q.db.ExecContext(ctx, saveWindow,
		arg.ProjectID,
		arg.Start,
		arg.End,
		arg.Text,
		arg.Ordinal,
	)
	return err
}

const windowsExist = `-- name: WindowsExist :one
SELECT EXISTS(SELECT 1 FROM text_windows WHERE project_id = ?)
`

func (q *Queries) WindowsExist(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, windowsExist, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
