// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
// ./internal/views/settings.templ

package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"

	"github.com/cork89/clippers/internal/types"
)

// SettingsData holds data for rendering the settings modal
type SettingsData struct {
	ProjectName string
	Settings    *types.ProjectSettings
}

// ProjectSettingsModal renders the project settings modal
func ProjectSettingsModal(data SettingsData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"settings-modal\" class=\"modal hidden\"><div class=\"modal-content settings-modal\"><div class=\"modal-header\"><h3>Project Settings</h3><button class=\"modal-close\" onclick=\"closeSettingsModal()\">×</button></div><div class=\"modal-body\"><form id=\"settings-form\" class=\"settings-form\"><div class=\"settings-section\"><h4>Video</h4><div class=\"form-group\"><label for=\"settings-shader\" class=\"form-label\">Shader Effect</label> <select id=\"settings-shader\" name=\"shader\" class=\"form-select\" onchange=\"previewShaderOnEditor(this.value)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, shader := range types.ShaderOptions() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(string(shader.Value))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/settings.templ`, Line: 33, Col: 38}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" selected=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Settings != nil && data.Settings.Shader == string(shader.Value))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/settings.templ`, Line: 34, Col: 89}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(shader.Label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/settings.templ`, Line: 36, Col: 24}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</select></div><div class=\"form-group\"><label for=\"settings-aspects\" class=\"form-label\">Aspect Ratios</label><div class=\"form-multi-select\" id=\"aspects-multi-select\"><div class=\"multi-select-container\" onclick=\"toggleAspectsDropdown()\"><span class=\"multi-select-placeholder\">Select aspect ratios...</span></div><div class=\"multi-select-dropdown\" id=\"aspects-dropdown\"><div class=\"multi-select-option\" data-value=\"1x1\" onclick=\"toggleAspect(&#39;1x1&#39;)\"><span>1:1 (Square)</span> <span class=\"check-icon\">✓</span></div><div class=\"multi-select-option\" data-value=\"16x9\" onclick=\"toggleAspect(&#39;16x9&#39;)\"><span>16:9 (Landscape)</span> <span class=\"check-icon\">✓</span></div><div class=\"multi-select-option\" data-value=\"9x16\" onclick=\"toggleAspect(&#39;9x16&#39;)\"><span>9:16 (Portrait)</span> <span class=\"check-icon\">✓</span></div></div></div><input type=\"hidden\" id=\"settings-aspects\" name=\"aspects\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(getAspects(data.Settings))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/settings.templ`, Line: 62, Col: 98}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"></div></div><div class=\"settings-section\"><h4>Subtitles</h4><div class=\"settings-form-row\"><div class=\"form-group\"><label for=\"settings-font-size\" class=\"form-label\">Font Size</label> <input type=\"number\" id=\"settings-font-size\" name=\"font_size\" class=\"form-input\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", getFontSize(data.Settings)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/settings.templ`, Line: 75, Col: 62}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" min=\"10\" max=\"200\"></div><div class=\"form-group\"><label for=\"settings-subtitle-margin\" class=\"form-label\">Subtitle Margin</label> <input type=\"number\" id=\"settings-subtitle-margin\" name=\"subtitle_margin\" class=\"form-input\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", getSubtitleMargin(data.Settings)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/settings.templ`, Line: 87, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" min=\"0\" max=\"200\"></div></div></div><div class=\"settings-section\"><h4>Effects</h4><div class=\"form-group\"><label for=\"settings-blur\" class=\"form-label\">Blur Strength</label><div class=\"slider-container\"><input type=\"range\" id=\"settings-blur\" name=\"blur_strength\" class=\"form-input\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", getBlurStrength(data.Settings)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/settings.templ`, Line: 104, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" min=\"0\" max=\"50\" oninput=\"updateSliderValue(this)\"> <span class=\"slider-value\" id=\"blur-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", getBlurStrength(data.Settings)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/settings.templ`, Line: 109, Col: 102}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</span></div></div></div></form></div><div class=\"modal-footer\"><button class=\"btn btn-secondary\" onclick=\"closeSettingsModal()\">Cancel</button> <button class=\"btn btn-primary\" onclick=\"saveSettings()\">Save Settings</button></div></div></div><script>\n\t\t// Initialize aspects multi-select after modal is loaded\n\t\tinitAspectsFromValue(document.getElementById('settings-aspects')?.value || '1x1,16x9,9x16');\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getFPS(s *types.ProjectSettings) int {
	if s == nil || s.FPS == 0 {
		return 24
	}
	return s.FPS
}

func getAspects(s *types.ProjectSettings) string {
	if s == nil || s.Aspects == "" {
		return "1x1,16x9,9x16"
	}
	return s.Aspects
}

func getFontSize(s *types.ProjectSettings) int {
	if s == nil || s.FontSize == 0 {
		return 60
	}
	return s.FontSize
}

func getSubtitleMargin(s *types.ProjectSettings) int {
	if s == nil || s.SubtitleMargin == 0 {
		return 20
	}
	return s.SubtitleMargin
}

func getMinShotSec(s *types.ProjectSettings) float64 {
	if s == nil || s.MinShotSec == 0 {
		return 5.0
	}
	return s.MinShotSec
}

func getMaxWords(s *types.ProjectSettings) int {
	if s == nil || s.MaxWords == 0 {
		return 5
	}
	return s.MaxWords
}

func getBlurStrength(s *types.ProjectSettings) int {
	if s == nil || s.BlurStrength == 0 {
		return 20
	}
	return s.BlurStrength
}

// SettingsButton renders the settings button
func SettingsButton() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var10 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var10 == nil {
			templ_7745c5c3_Var10 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<button id=\"settings-btn\" class=\"btn btn-secondary\" onclick=\"openSettingsModal()\">⚙️ Settings</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
